[package]
authors = ["Tyler Boright <ru.lai.development@gmail.com>"]
description = "HashMap / Tuple-backed Markov Chains"
edition = "2018"
license = "MIT"
name = "markov"
version = "0.1.0"

[dependencies]
rand = "0.7"
